module.exports.descriptors = [
    'Elite Combat Academy',
'Iron Fist MMA',
'Apex Martial Arts',
'Phoenix Fight Club',
'Titan MMA Academy',
'Vanguard Martial Studio',
'Dominance MMA Gym',
'Valor Fight Center',
'Precision Striking Academy',
'Renegade Submission Training',
'Ascendant Combat Institute',
'Grizzly Claw MMA',
'Resilience Martial Arts',
'Black Belt Brigade',
'Pinnacle Punch Academy',
'Thunderstrike Training Center',
'Ignite Fight Fusion',
'Savage Ground Game Gym',
'Nova Strike MMA',
'Zenith Warrior Training'
]

// module.exports.places = [
//     'Flats',
//     'Village',
//     'Canyon',
//     'Pond',
//     'Group Camp',
//     'Horse Camp',
//     'Ghost Town',
//     'Camp',
//     'Dispersed Camp',
//     'Backcountry',
//     'River',
//     'Creek',
//     'Creekside',
//     'Bay',
//     'Spring',
//     'Bayshore',
//     'Sands',
//     'Mule Camp',
//     'Hunting Camp',
//     'Cliffs',
//     'Hollow'
// ]
